name: Main CI workflow

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-22.04

    steps:
      - name: Check out code
        uses: actions/checkout@v4.1.1

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run Tests
        run: npm test

  sonar:
    name: SonarCloud Scan
    runs-on: ubuntu-22.04
    needs: lint

    steps:
      - name: Check out code
        uses: actions/checkout@v4.1.1
        
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
