name: Main CI workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    name: main
    timeout-minutes: 15
    runs-on: ubuntu-22.04

    steps:
      - name: Check out code
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 2

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Linting
        run: npm run lint

      - name: Unit and integration tests
        run: npm test

      - name: SonarCloud Scan
        # continue-on-error: true
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
