name: Main CI workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    name: main
    timeout-minutes: 15
    runs-on: ubuntu-22.04

    steps:
      - name: Check out code
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 2

      - name: Cache turbo build setup
        uses: actions/cache@v4.0.2
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2
        with:
          node-version-file: '.nvmrc'

      - name: Install Yarn
        run: corepack enable && corepack prepare yarn@stable --activate

      - name: Cache Yarn dependencies
        uses: actions/cache@v4
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install

      - name: Linting
        run: yarn run lint

      - name: Unit and integration tests
        run: yarn run test

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
